// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3QHhurZJyxVZLyFyYcanGkRaj9x7RXLs',
    appId: '1:649205325956:web:9ab3501452328e0c69e2d1',
    messagingSenderId: '649205325956',
    projectId: 'citylightsflutter',
    authDomain: 'citylightsflutter.firebaseapp.com',
    storageBucket: 'citylightsflutter.appspot.com',
    measurementId: 'G-WJMK7D082B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6BkOrdXFWbkgZEafFqxIOJIm7zVTcqE',
    appId: '1:649205325956:android:25e3fb373f38147c69e2d1',
    messagingSenderId: '649205325956',
    projectId: 'citylightsflutter',
    storageBucket: 'citylightsflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3YXeZ2tiThzlIweVES5NFH3FAa6NessM',
    appId: '1:649205325956:ios:5c5e6ed4d568cb0b69e2d1',
    messagingSenderId: '649205325956',
    projectId: 'citylightsflutter',
    storageBucket: 'citylightsflutter.appspot.com',
    iosBundleId: 'com.example.citylights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3YXeZ2tiThzlIweVES5NFH3FAa6NessM',
    appId: '1:649205325956:ios:20613d7df002d27869e2d1',
    messagingSenderId: '649205325956',
    projectId: 'citylightsflutter',
    storageBucket: 'citylightsflutter.appspot.com',
    iosBundleId: 'com.example.citylights.RunnerTests',
  );
}
